export const navItems = [
  { label: "Portfolio", href: "/portfolio" },
  { label: "Services", href: "/#services" },
  { label: "About", href: "/#about" },
  { label: "Contact", href: "/#contact" },
];

export const services = [
  {
    title: "Brand Design & Logos",
    copy: "Deep industry research paired with custom logo design and high-level visual identity systems.",
    tokenSrc: "/assets/services/service-brand-design-token.png",
    tokenAlt: "3D graphic design token",
  },
  {
    title: "Social & Campaign Planning",
    copy: "Niche-focused campaign planning, creative direction, and layouts for your digital feeds.",
    tokenSrc: "/assets/services/service-social-campaign-token.png",
    tokenAlt: "3D social media network token",
  },
  {
    title: "Video Production",
    copy: "High-quality video concepts, filming, and platform-ready content designed to convert viewers.",
    tokenSrc: "/assets/services/service-video-production-token.png",
    tokenAlt: "3D video production token",
  },
  {
    title: "Brand Photography",
    copy: "Professional lifestyle and brand imagery shaped for your website and digital channels.",
    tokenSrc: "/assets/services/service-brand-photography-token.png",
    tokenAlt: "3D photography token",
  },
  {
    title: "Event Coverage",
    copy: "On-site media capture to turn your live events into high-impact digital campaign assets.",
    tokenSrc: "/assets/services/service-event-coverage-token.png",
    tokenAlt: "3D content creation token",
  },
  {
    title: "Digital Brand Assets",
    copy: "Launch-ready templates for social media graphics, profile layouts, and digital banners.",
    tokenSrc: "/assets/services/service-digital-brand-assets-token.png",
    tokenAlt: "3D digital marketing token",
  },
];

const portfolioItems = [
  {
    title: "Launch Content System",
    category: "Social system",
    metric: "Launch-ready direction",
    imagePosition: "100% 100%",
  },
  {
    title: "Creator-Led Product Story",
    category: "Content suite",
    metric: "Short-form direction",
    imagePosition: "33.333% 0%",
  },
  {
    title: "Identity Refresh Kit",
    category: "Visual identity",
    metric: "Brand kit direction",
    imagePosition: "66.667% 0%",
  },
  {
    title: "Studio Product Shoot",
    category: "Photography",
    metric: "Gallery direction",
    imagePosition: "100% 0%",
  },
  {
    title: "Editorial Video Cutdown",
    category: "Video system",
    metric: "Multi-platform direction",
    imagePosition: "0% 100%",
  },
  {
    title: "Performance Dashboard",
    category: "Marketing",
    metric: "Reporting direction",
    imagePosition: "33.333% 100%",
  },
  {
    title: "Campaign Moodboard",
    category: "Brand Direction",
    metric: "Visual strategy",
    imagePosition: "66.667% 100%",
  },
  {
    title: "Mobile Feed Direction",
    category: "Creative Strategy",
    metric: "Content matrix",
    imagePosition: "0% 0%",
  },
];

const driveThumb = (id: string) =>
  `https://drive.google.com/thumbnail?id=${id}&sz=w1600`;

const drivePreview = (id: string) =>
  `https://drive.google.com/file/d/${id}/preview`;

const createDriveItems = (
  title: string,
  category: string,
  metric: string,
  ids: string[],
  mediaType: "image" | "video" = "image",
  orientation: "portrait" | "landscape" = "portrait",
) =>
  ids.map((id, index) => ({
    title: `${title} ${index + 1}`,
    category,
    metric,
    imageSrc: driveThumb(id),
    ...(mediaType === "video"
      ? {
          mediaType,
          previewSrc: drivePreview(id),
          orientation,
        }
      : {}),
  }));

const createDriveVideoItems = (
  title: string,
  category: string,
  metric: string,
  ids: string[],
  orientation: "portrait" | "landscape" = "portrait",
) => createDriveItems(title, category, metric, ids, "video", orientation);

const contentCreationItemsUnordered = [
  {
    title: "The Bar & Grill 1",
    category: "Content creation",
    metric: "AQM7KoOyVuW nru9p-JeVZ6I0XoS2t0AbacgSiAkVATHsHa3A9CE1XILHU2eNB02zKm8EtN2MX4jo673O7grrArnZGy9fvxG-e4",
    imageSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-01.jpg",
    videoSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-01.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "The Bar & Grill",
  },
  {
    title: "The Bar & Grill 2",
    category: "Content creation",
    metric: "AQM9DyuBTmzg7uPmpb0OTIECZm96bVSPwIendmKMujWOnD9H2nfdFJIDmKagh62bLzm J4qcLObuftERgGKMn vl1C6HF6u5MW4",
    imageSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-02.jpg",
    videoSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-02.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "The Bar & Grill",
  },
  {
    title: "The Bar & Grill 3",
    category: "Content creation",
    metric: "AQMI7aP6EE3xfFqVRXKh91U7HF9cXJ60RfNSyYvcHKvA1qg9lj9x5Q3gI4UKdFC2K8qfzB2FCnL0HB4sWzt1qlWQJ oOwspuE8Q",
    imageSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-03.jpg",
    videoSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-03.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "The Bar & Grill",
  },
  {
    title: "The Bar & Grill 4",
    category: "Content creation",
    metric: "AQMvz7P5OYsSI-VUqtsgyEQw7B4ByKBBKoboJaAx78V-jsHiJ3y0E2joIPt1kh QFTtGJ6d0o43qF1dBuPfj9VHHTXTqR2dFepo",
    imageSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-04.jpg",
    videoSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-04.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "The Bar & Grill",
  },
  {
    title: "The Bar & Grill 5",
    category: "Content creation",
    metric: "AQN4zIhgD PzutlJeZ56t8dY2hfnZ3A9sRIPXqYT 4JbDNfM7CVPIBoH2UNGmSb6BRHE zTgzDiGQaLiHUmNZUsv2jjyN11GyVg",
    imageSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-05.jpg",
    videoSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-05.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "The Bar & Grill",
  },
  {
    title: "The Bar & Grill 6",
    category: "Content creation",
    metric: "AQN9i-zmhy0srniWvH0eijecj85MP9lSJLsQUtfOuuQn6X4zEq-Rk56VGukiG0OZw mjBdPrAS6DhBYJv0S-In3phnxSJZklF84",
    imageSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-06.jpg",
    videoSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-06.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "The Bar & Grill",
  },
  {
    title: "The Bar & Grill 7",
    category: "Content creation",
    metric: "AQOkYF0XbHfe7fXAYNy2hTN1EsfOhLTtcE4fi3owTyyOczLHs2x57YI O6A px5iZqx1cAOFLGsGDRLSEykfko6-d9ytafeUW 8",
    imageSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-07.jpg",
    videoSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-07.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "The Bar & Grill",
  },
  {
    title: "The Bar & Grill 8",
    category: "Content creation",
    metric: "AQOPN8uYDyYqdm7i0bXNfkq7G2aQipkz5E3n1e91R0a1MOP RI 0as3C1l8Rt jl b7YR K1hikKR0Y7zffS5ueQ9dsjNjrPVM",
    imageSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-08.jpg",
    videoSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-08.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "The Bar & Grill",
  },
  {
    title: "The Bar & Grill 9",
    category: "Content creation",
    metric: "AQOroFPPmjlwOVBf0rZCg4xqcP7DcS5jRYGxGdErFLgTXR1raNRuJfY7KURJnclO9Fg76nrVEoB6pymPnbPNUr0dlQDtMVlVADA",
    imageSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-09.jpg",
    videoSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-09.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "The Bar & Grill",
  },
  {
    title: "The Bar & Grill 10",
    category: "Content creation",
    metric: "AQOSxrkT3cJcmGZbIPPWl CRXvavAaPp9yf6NOio-lc9pddise1VZh lHXXAl-YTJmm8sw0SS8 s4wtE iwQ8TMijryssh1Ujk0",
    imageSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-10.jpg",
    videoSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-10.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "The Bar & Grill",
  },
  {
    title: "The Bar & Grill 11",
    category: "Content creation",
    metric: "AQP9M25V8904jN7o094Dku8h PvxN51EaBAGnB6h3ysgwDRTxENW7Hfhrp6z0E7tNJuM2bCDyZtqv32-EPdfWIdm1Zow73tdq6A",
    imageSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-11.jpg",
    videoSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-11.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "The Bar & Grill",
  },
  {
    title: "The Bar & Grill 12",
    category: "Content creation",
    metric: "AQPMvq3-k6HlbjZUe-kPGdBahnBUqw0Ies6qvMasK71lKDo-cA5Ewerr1blHfNl00ubYlDJRf27z Dle0OTcRNuM1mdfmQEfhDQ",
    imageSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-12.jpg",
    videoSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-12.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "The Bar & Grill",
  },
  {
    title: "The Bar & Grill 13",
    category: "Content creation",
    metric: "AQPpJduPQ2n2dxURJpgONwsWqXfVtaGhTLHgCMoNJAXotRSLQbuf80DgrzDvGCFVw79epxaDKq5Ytoc7o VTXbUf81crkmg-iUs",
    imageSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-13.jpg",
    videoSrc: "/assets/portfolio/content-creation/the-bar-and-grill/the-bar-and-grill-13.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "The Bar & Grill",
  },
  {
    title: "Beacon 57 1",
    category: "Content creation",
    metric: "2 Chirstmas Holidays",
    imageSrc: "/assets/portfolio/content-creation/beacon-57/beacon-57-01.jpg",
    videoSrc: "/assets/portfolio/content-creation/beacon-57/beacon-57-01.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Beacon 57",
  },
  {
    title: "Beacon 57 2",
    category: "Content creation",
    metric: "8 Spicy Marg",
    imageSrc: "/assets/portfolio/content-creation/beacon-57/beacon-57-02.jpg",
    videoSrc: "/assets/portfolio/content-creation/beacon-57/beacon-57-02.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Beacon 57",
  },
  {
    title: "Beacon 57 3",
    category: "Content creation",
    metric: "Content 2 GLimpse of Beacon 57",
    imageSrc: "/assets/portfolio/content-creation/beacon-57/beacon-57-03.jpg",
    videoSrc: "/assets/portfolio/content-creation/beacon-57/beacon-57-03.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Beacon 57",
  },
  {
    title: "Beacon 57 4",
    category: "Content creation",
    metric: "Content 5 Every Story",
    imageSrc: "/assets/portfolio/content-creation/beacon-57/beacon-57-04.jpg",
    videoSrc: "/assets/portfolio/content-creation/beacon-57/beacon-57-04.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Beacon 57",
  },
  {
    title: "Beacon 57 5",
    category: "Content creation",
    metric: "February 17 2026",
    imageSrc: "/assets/portfolio/content-creation/beacon-57/beacon-57-05.jpg",
    videoSrc: "/assets/portfolio/content-creation/beacon-57/beacon-57-05.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Beacon 57",
  },
  {
    title: "Beacon 57 6",
    category: "Content creation",
    metric: "Stand me beer & cocktail",
    imageSrc: "/assets/portfolio/content-creation/beacon-57/beacon-57-06.jpg",
    videoSrc: "/assets/portfolio/content-creation/beacon-57/beacon-57-06.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Beacon 57",
  },
  {
    title: "Beacon 57 7",
    category: "Content creation",
    metric: "video-output-105DB9CD-2E49-463C-AAF1-5D2F341691CC-1",
    imageSrc: "/assets/portfolio/content-creation/beacon-57/beacon-57-07.jpg",
    videoSrc: "/assets/portfolio/content-creation/beacon-57/beacon-57-07.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Beacon 57",
  },
  {
    title: "Crawfish for a Cause 1",
    category: "Content creation",
    metric: "AQMg0kCdWTqmdX88E3Ex OsTZEFUzAPnJnRbTejlDa u2sz3ZNFi3BEXyrGIgSqLjfQfNTm771qVSRBi0cac2qM5QkClVQ0LHY",
    imageSrc: "/assets/portfolio/content-creation/crawfish-for-a-cause/crawfish-for-a-cause-01.jpg",
    videoSrc: "/assets/portfolio/content-creation/crawfish-for-a-cause/crawfish-for-a-cause-01.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Crawfish for a Cause",
  },
  {
    title: "Crawfish for a Cause 2",
    category: "Content creation",
    metric: "AQMge2RcykLKXNl9BcxMbpwvsZyKWQm5tZMFtGmi5BDk7geW3Q gfnfx-GnnChNrSMiKr2WtfNrhoIHHiK- 7cGbx0nDI0NBbhA",
    imageSrc: "/assets/portfolio/content-creation/crawfish-for-a-cause/crawfish-for-a-cause-02.jpg",
    videoSrc: "/assets/portfolio/content-creation/crawfish-for-a-cause/crawfish-for-a-cause-02.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Crawfish for a Cause",
  },
  {
    title: "Crawfish for a Cause 3",
    category: "Content creation",
    metric: "AQNghB4BCrouncSv6Qtlx kGswhsDZDFS3-sh0LzIinVVziq6At2qdZ9UQRiuwHJLiGWLv2sW2B6J2kUgYCqfAeGFxdYnhvUKfA",
    imageSrc: "/assets/portfolio/content-creation/crawfish-for-a-cause/crawfish-for-a-cause-03.jpg",
    videoSrc: "/assets/portfolio/content-creation/crawfish-for-a-cause/crawfish-for-a-cause-03.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Crawfish for a Cause",
  },
  {
    title: "Crawfish for a Cause 4",
    category: "Content creation",
    metric: "AQNJoWWlH02qvz2By iz1E7cLggd6uWB9OxELgevtPUO7LNsbhrGOeXFj86Yya6xSD7rlGvfZszPBdfIBmbm91x0Ob3aucUMwTOyw8z5irY1dQ",
    imageSrc: "/assets/portfolio/content-creation/crawfish-for-a-cause/crawfish-for-a-cause-04.jpg",
    videoSrc: "/assets/portfolio/content-creation/crawfish-for-a-cause/crawfish-for-a-cause-04.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Crawfish for a Cause",
  },
  {
    title: "Crawfish for a Cause 5",
    category: "Content creation",
    metric: "AQOMPF3W4zzeaiBAAqPBMPt1o8uDnyV7iNxoaMr67YvtWBA4iBqvsXTz8Hb2Zihx4xQbhpAA356EzAtxnQ9Fwy40--89xWgBPsc",
    imageSrc: "/assets/portfolio/content-creation/crawfish-for-a-cause/crawfish-for-a-cause-05.jpg",
    videoSrc: "/assets/portfolio/content-creation/crawfish-for-a-cause/crawfish-for-a-cause-05.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Crawfish for a Cause",
  },
  {
    title: "Crawfish for a Cause 6",
    category: "Content creation",
    metric: "AQOrI2SgmvS8ZVlhMaFkl1uHHMjtufmJi3Ij5ahWbeWTVAa90RAoWU-hW8sA40D SsxTUx6JiA4Qm5GyBaidO8C18fjtimvU2Z0",
    imageSrc: "/assets/portfolio/content-creation/crawfish-for-a-cause/crawfish-for-a-cause-06.jpg",
    videoSrc: "/assets/portfolio/content-creation/crawfish-for-a-cause/crawfish-for-a-cause-06.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Crawfish for a Cause",
  },
  {
    title: "Crawfish for a Cause 7",
    category: "Content creation",
    metric: "AQPQwRHRQ1pGJ0UHhT gNnBdoqRlrF7CX7wBcxQyHS8uiXpgNoA6n4Dp8wkWG2cl5bo-ECkf78WAGNFta4uSiy078HVIhP24-C2lNdE6DCDMUw",
    imageSrc: "/assets/portfolio/content-creation/crawfish-for-a-cause/crawfish-for-a-cause-07.jpg",
    videoSrc: "/assets/portfolio/content-creation/crawfish-for-a-cause/crawfish-for-a-cause-07.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Crawfish for a Cause",
  },
  {
    title: "Habitat for Humanity 1",
    category: "Content creation",
    metric: "AQNmCIj316Q4C2s1Nr qsip bevOcCk0GhHN0rtSu2bQ0AwsYbCJqq1laZTPBh0oYv5qIMA CqdrgiMEmmHgAwXAc5NKPpuh1aA",
    imageSrc: "/assets/portfolio/content-creation/habitat-for-humanity/habitat-for-humanity-01.jpg",
    videoSrc: "/assets/portfolio/content-creation/habitat-for-humanity/habitat-for-humanity-01.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Habitat for Humanity",
  },
  {
    title: "Habitat for Humanity 2",
    category: "Content creation",
    metric: "AQPNySQb8cKGLdwCftyBsIKNTb5h2ad5QcFhBc8DoMDij6KYJxpd9AMmWxQuTGjZAWFx7QbinzcrMy8C4YBilfM0Ic7OFvnPRmrqH9-94g",
    imageSrc: "/assets/portfolio/content-creation/habitat-for-humanity/habitat-for-humanity-02.jpg",
    videoSrc: "/assets/portfolio/content-creation/habitat-for-humanity/habitat-for-humanity-02.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Habitat for Humanity",
  },
  {
    title: "Harbor Half Marathon 1",
    category: "Content creation",
    metric: "AQM67fzIg3 tyToFT5hcKA3p9CpZopDOe-B5XxdaRQ0GWN4nQg 04q7d5WLtWtzADsH3pmfke551LiICrpHGSH7NAqcryRy3klI",
    imageSrc: "/assets/portfolio/content-creation/harbor-half-marathon/harbor-half-marathon-01.jpg",
    videoSrc: "/assets/portfolio/content-creation/harbor-half-marathon/harbor-half-marathon-01.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Harbor Half Marathon",
  },
  {
    title: "Harbor Half Marathon 2",
    category: "Content creation",
    metric: "AQN-zqz9ntG-Xt6BOxS4l-jeu6O ImvX7lsFV-7accjdnqjzG lBKrbZbT9kfzgVt3BXQ0OIniKAVUoxH2NegRu9OjQmBedwSkM",
    imageSrc: "/assets/portfolio/content-creation/harbor-half-marathon/harbor-half-marathon-02.jpg",
    videoSrc: "/assets/portfolio/content-creation/harbor-half-marathon/harbor-half-marathon-02.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Harbor Half Marathon",
  },
  {
    title: "Harbor Half Marathon 3",
    category: "Content creation",
    metric: "AQN2ohHFuEouEJkYdLRp oB3zGnVX7h7CzJ8T-TJwG5aBHhHgKc9spEMnmvRoDPk-KMBpQku4iOKtRT3dScuGJVH gG1vdTn3mw",
    imageSrc: "/assets/portfolio/content-creation/harbor-half-marathon/harbor-half-marathon-03.jpg",
    videoSrc: "/assets/portfolio/content-creation/harbor-half-marathon/harbor-half-marathon-03.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Harbor Half Marathon",
  },
  {
    title: "Harbor Half Marathon 4",
    category: "Content creation",
    metric: "AQOtkEQ2 CrX6LGkd3B6hQe1KGcCD8leEJek8 FynSm4LC-W866sEKYzSqCrJzhkhxiSw7EpyUlKsoamzz5N7g izIFPUpsCCcIrfHmuWlTlUA",
    imageSrc: "/assets/portfolio/content-creation/harbor-half-marathon/harbor-half-marathon-04.jpg",
    videoSrc: "/assets/portfolio/content-creation/harbor-half-marathon/harbor-half-marathon-04.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Harbor Half Marathon",
  },
  {
    title: "Harbor Half Marathon 5",
    category: "Content creation",
    metric: "AQOWtqK4wNd4xpKGo4C91vWVcFp7MY21FBgibPjwNPlcpaKqV0tWJYT4KtSdozau22iJMaS QR8uga7-xCntlWvC6J2oUGd-DJQ",
    imageSrc: "/assets/portfolio/content-creation/harbor-half-marathon/harbor-half-marathon-05.jpg",
    videoSrc: "/assets/portfolio/content-creation/harbor-half-marathon/harbor-half-marathon-05.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Harbor Half Marathon",
  },
  {
    title: "Harbor Half Marathon 6",
    category: "Content creation",
    metric: "AQPm3BhoCu-9Ge-bjZXjkagHe21cHJOz32UHXGVlpZx0B5e5eCWwOekYpH-JGO3uXUZV-URd1MypWF70rwngjrc85DPofvIrnqsod05xYl0IWw",
    imageSrc: "/assets/portfolio/content-creation/harbor-half-marathon/harbor-half-marathon-06.jpg",
    videoSrc: "/assets/portfolio/content-creation/harbor-half-marathon/harbor-half-marathon-06.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Harbor Half Marathon",
  },
  {
    title: "Harbor Half Marathon 7",
    category: "Content creation",
    metric: "AQPQrwCfnPeNE-bQ2GH7O ZQf5rEQ3AE cjGdukfpWZYTi6V8K2GZWGoec7uQo0kFSe4d4Xus412KgzaPnMZ-avpVhKb1ncZeV8",
    imageSrc: "/assets/portfolio/content-creation/harbor-half-marathon/harbor-half-marathon-07.jpg",
    videoSrc: "/assets/portfolio/content-creation/harbor-half-marathon/harbor-half-marathon-07.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Harbor Half Marathon",
  },
  {
    title: "Hotel Lydia 1",
    category: "Content creation",
    metric: "Content 14 Premium Two Queen Room",
    imageSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-01.jpg",
    videoSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-01.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Hotel Lydia",
  },
  {
    title: "Hotel Lydia 2",
    category: "Content creation",
    metric: "Content 3 Reel Hotel Lydia",
    imageSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-02.jpg",
    videoSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-02.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Hotel Lydia",
  },
  {
    title: "Hotel Lydia 3",
    category: "Content creation",
    metric: "Content 5 Reel Premium 2 Queen Kitchenette",
    imageSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-03.jpg",
    videoSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-03.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Hotel Lydia",
  },
  {
    title: "Hotel Lydia 4",
    category: "Content creation",
    metric: "Content 9 Chapel on the Dunes 5mins",
    imageSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-04.jpg",
    videoSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-04.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Hotel Lydia",
  },
  {
    title: "Hotel Lydia 5",
    category: "Content creation",
    metric: "USED Aspirarational Walking into work after being name-dropped in a 5-star review",
    imageSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-05.jpg",
    videoSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-05.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Hotel Lydia",
  },
  {
    title: "Hotel Lydia 6",
    category: "Content creation",
    metric: "USED Commercial Things in our premium room that make sense",
    imageSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-06.jpg",
    videoSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-06.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Hotel Lydia",
  },
  {
    title: "Hotel Lydia 7",
    category: "Content creation",
    metric: "USED Funny When your coworker is twice your age",
    imageSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-07.jpg",
    videoSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-07.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Hotel Lydia",
  },
  {
    title: "Hotel Lydia 8",
    category: "Content creation",
    metric: "USED Funny your ex blocked you",
    imageSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-08.jpg",
    videoSrc: "/assets/portfolio/content-creation/hotel-lydia/hotel-lydia-08.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Hotel Lydia",
  },
  {
    title: "Memory Machine 1",
    category: "Content creation",
    metric: "AQNc72Mvg8IuABCyXoZgBSTTUl-iSBPYF9eZ4lSqgjdbjDrfoR3ecNfFoohG-mIGDdCXxTYQhB9G5NrXwkw1mLl3p4ngFCJlkZw",
    imageSrc: "/assets/portfolio/content-creation/memory-machine/memory-machine-01.jpg",
    videoSrc: "/assets/portfolio/content-creation/memory-machine/memory-machine-01.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Memory Machine",
  },
  {
    title: "Memory Machine 2",
    category: "Content creation",
    metric: "AQOcyVb3mdSHEddSBrQUSz Morm5AHl bJ49u9n8F3Sfgmc4UhERgwOvceL4b6VMaPjPuKDlz9buFmZi5xjtzNgTmmOH42R9VQQ",
    imageSrc: "/assets/portfolio/content-creation/memory-machine/memory-machine-02.jpg",
    videoSrc: "/assets/portfolio/content-creation/memory-machine/memory-machine-02.mp4",
    mediaType: "video",
    orientation: "portrait",
    display: "story",
    account: "Memory Machine",
  },
];

const contentCreationAccountOrder = [
  "Hotel Lydia",
  "Beacon 57",
  "The Bar & Grill",
  "Crawfish for a Cause",
  "Harbor Half Marathon",
  "Habitat for Humanity",
  "Memory Machine",
];

const contentCreationAccountRank = new Map(
  contentCreationAccountOrder.map((account, index) => [account, index]),
);

const contentCreationItems = [...contentCreationItemsUnordered].sort(
  (left, right) =>
    (contentCreationAccountRank.get(left.account) ?? Number.MAX_SAFE_INTEGER) -
    (contentCreationAccountRank.get(right.account) ?? Number.MAX_SAFE_INTEGER),
);

const eventCoverageItems = [
  {
    title: "Marine Corps Ball 1",
    category: "Event coverage",
    metric: "Formal event documentation",
    imageSrc: "/assets/portfolio/event-coverage/marine-corps-ball-01.jpg",
  },
  {
    title: "Marine Corps Ball 2",
    category: "Event coverage",
    metric: "Formal event documentation",
    imageSrc: "/assets/portfolio/event-coverage/marine-corps-ball-02.jpg",
  },
  {
    title: "Marine Corps Ball 3",
    category: "Event coverage",
    metric: "Formal event documentation",
    imageSrc: "/assets/portfolio/event-coverage/marine-corps-ball-03.jpg",
  },
  {
    title: "Marine Corps Ball 4",
    category: "Event coverage",
    metric: "Formal event documentation",
    imageSrc: "/assets/portfolio/event-coverage/marine-corps-ball-04.jpg",
  },
  {
    title: "Marine Corps Ball 5",
    category: "Event coverage",
    metric: "Formal event documentation",
    imageSrc: "/assets/portfolio/event-coverage/marine-corps-ball-05.jpg",
  },
  {
    title: "Marine Corps Ball 6",
    category: "Event coverage",
    metric: "Formal event documentation",
    imageSrc: "/assets/portfolio/event-coverage/marine-corps-ball-06.jpg",
  },
  {
    title: "Marine Corps Ball 7",
    category: "Event coverage",
    metric: "Formal event documentation",
    imageSrc: "/assets/portfolio/event-coverage/marine-corps-ball-07.jpg",
  },
  {
    title: "Marine Corps Ball 8",
    category: "Event coverage",
    metric: "Formal event documentation",
    imageSrc: "/assets/portfolio/event-coverage/marine-corps-ball-08.jpg",
  },
  {
    title: "Marine Corps Ball 9",
    category: "Event coverage",
    metric: "Formal event documentation",
    imageSrc: "/assets/portfolio/event-coverage/marine-corps-ball-09.jpg",
  },
  {
    title: "Marine Corps Ball 10",
    category: "Event coverage",
    metric: "Formal event documentation",
    imageSrc: "/assets/portfolio/event-coverage/marine-corps-ball-10.jpg",
  },
  {
    title: "Associated Builders 1",
    category: "Event coverage",
    metric: "Industry event coverage",
    imageSrc: "/assets/portfolio/event-coverage/associated-builders-01.jpg",
  },
  {
    title: "Associated Builders 2",
    category: "Event coverage",
    metric: "Industry event coverage",
    imageSrc: "/assets/portfolio/event-coverage/associated-builders-02.jpg",
  },
  {
    title: "Associated Builders 3",
    category: "Event coverage",
    metric: "Industry event coverage",
    imageSrc: "/assets/portfolio/event-coverage/associated-builders-03.jpg",
  },
  {
    title: "Associated Builders 4",
    category: "Event coverage",
    metric: "Industry event coverage",
    imageSrc: "/assets/portfolio/event-coverage/associated-builders-04.jpg",
  },
  {
    title: "Coastal Bend Fil-Am Association 1",
    category: "Event coverage",
    metric: "Community event photography",
    imageSrc: "/assets/portfolio/event-coverage/coastal-bend-fil-am-association-01.jpg",
  },
  {
    title: "Coastal Bend Fil-Am Association 2",
    category: "Event coverage",
    metric: "Community event photography",
    imageSrc: "/assets/portfolio/event-coverage/coastal-bend-fil-am-association-02.jpg",
  },
  {
    title: "Coastal Bend Fil-Am Association 3",
    category: "Event coverage",
    metric: "Community event photography",
    imageSrc: "/assets/portfolio/event-coverage/coastal-bend-fil-am-association-03.jpg",
  },
  {
    title: "Coastal Bend Fil-Am Association 4",
    category: "Event coverage",
    metric: "Community event photography",
    imageSrc: "/assets/portfolio/event-coverage/coastal-bend-fil-am-association-04.jpg",
  },
  {
    title: "Coastal Bend Fil-Am Association 5",
    category: "Event coverage",
    metric: "Community event photography",
    imageSrc: "/assets/portfolio/event-coverage/coastal-bend-fil-am-association-05.jpg",
  },
  {
    title: "Coastal Bend Fil-Am Association 6",
    category: "Event coverage",
    metric: "Community event photography",
    imageSrc: "/assets/portfolio/event-coverage/coastal-bend-fil-am-association-06.jpg",
  },
  {
    title: "Coastal Bend Fil-Am Association 7",
    category: "Event coverage",
    metric: "Community event photography",
    imageSrc: "/assets/portfolio/event-coverage/coastal-bend-fil-am-association-07.jpg",
  },
  {
    title: "Coastal Bend Fil-Am Association 8",
    category: "Event coverage",
    metric: "Community event photography",
    imageSrc: "/assets/portfolio/event-coverage/coastal-bend-fil-am-association-08.jpg",
  },
  {
    title: "Education is Our Freedom 1",
    category: "Event coverage",
    metric: "Scholarship program moments",
    imageSrc: "/assets/portfolio/event-coverage/education-is-our-freedom-01.jpg",
  },
  {
    title: "Education is Our Freedom 2",
    category: "Event coverage",
    metric: "Scholarship program moments",
    imageSrc: "/assets/portfolio/event-coverage/education-is-our-freedom-02.jpg",
  },
  {
    title: "Education is Our Freedom 3",
    category: "Event coverage",
    metric: "Scholarship program moments",
    imageSrc: "/assets/portfolio/event-coverage/education-is-our-freedom-03.jpg",
  },
  {
    title: "Education is Our Freedom 4",
    category: "Event coverage",
    metric: "Scholarship program moments",
    imageSrc: "/assets/portfolio/event-coverage/education-is-our-freedom-04.jpg",
  },
  {
    title: "Education is Our Freedom 5",
    category: "Event coverage",
    metric: "Scholarship program moments",
    imageSrc: "/assets/portfolio/event-coverage/education-is-our-freedom-05.jpg",
  },
  {
    title: "Education is Our Freedom 6",
    category: "Event coverage",
    metric: "Scholarship program moments",
    imageSrc: "/assets/portfolio/event-coverage/education-is-our-freedom-06.jpg",
  },
  {
    title: "Education is Our Freedom 7",
    category: "Event coverage",
    metric: "Scholarship program moments",
    imageSrc: "/assets/portfolio/event-coverage/education-is-our-freedom-07.jpg",
  },
  {
    title: "Education is Our Freedom 8",
    category: "Event coverage",
    metric: "Scholarship program moments",
    imageSrc: "/assets/portfolio/event-coverage/education-is-our-freedom-08.jpg",
  },
  {
    title: "Habitat x Buc Days Build 1",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-01.jpg",
  },
  {
    title: "Habitat x Buc Days Build 2",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-02.jpg",
  },
  {
    title: "Habitat x Buc Days Build 3",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-03.jpg",
  },
  {
    title: "Habitat x Buc Days Build 4",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-04.jpg",
  },
  {
    title: "Habitat x Buc Days Build 5",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-05.jpg",
  },
  {
    title: "Habitat x Buc Days Build 6",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-06.jpg",
  },
  {
    title: "Habitat x Buc Days Build 7",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-07.jpg",
  },
  {
    title: "Habitat x Buc Days Build 8",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-08.jpg",
  },
  {
    title: "Habitat x Buc Days Build 9",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-09.jpg",
  },
  {
    title: "Habitat x Buc Days Build 10",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-10.jpg",
  },
  {
    title: "Habitat x Buc Days Build 11",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-11.jpg",
  },
  {
    title: "Habitat x Buc Days Build 12",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-12.jpg",
  },
  {
    title: "Habitat x Buc Days Build 13",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-13.jpg",
  },
  {
    title: "Habitat x Buc Days Build 14",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-14.jpg",
  },
  {
    title: "Habitat x Buc Days Build 15",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-15.jpg",
  },
  {
    title: "Habitat x Buc Days Build 16",
    category: "Event coverage",
    metric: "Nonprofit event coverage",
    imageSrc: "/assets/portfolio/event-coverage/habitat-x-buc-days-build-16.jpg",
  },
  {
    title: "Memory Machine 1",
    category: "Event coverage",
    metric: "Live experience coverage",
    imageSrc: "/assets/portfolio/event-coverage/memory-machine-01.jpg",
  },
  {
    title: "Memory Machine 2",
    category: "Event coverage",
    metric: "Live experience coverage",
    imageSrc: "/assets/portfolio/event-coverage/memory-machine-02.jpg",
  },
  {
    title: "Memory Machine 3",
    category: "Event coverage",
    metric: "Live experience coverage",
    imageSrc: "/assets/portfolio/event-coverage/memory-machine-03.jpg",
  },
  {
    title: "Memory Machine 4",
    category: "Event coverage",
    metric: "Live experience coverage",
    imageSrc: "/assets/portfolio/event-coverage/memory-machine-04.jpg",
  },
  {
    title: "Winsupply Corpus Christi 1",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-01.jpg",
  },
  {
    title: "Winsupply Corpus Christi 2",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-02.jpg",
  },
  {
    title: "Winsupply Corpus Christi 3",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-03.jpg",
  },
  {
    title: "Winsupply Corpus Christi 4",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-04.jpg",
  },
  {
    title: "Winsupply Corpus Christi 5",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-05.jpg",
  },
  {
    title: "Winsupply Corpus Christi 6",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-06.jpg",
  },
  {
    title: "Winsupply Corpus Christi 7",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-07.jpg",
  },
  {
    title: "Winsupply Corpus Christi 8",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-08.jpg",
  },
  {
    title: "Winsupply Corpus Christi 9",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-09.jpg",
  },
  {
    title: "Winsupply Corpus Christi 10",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-10.jpg",
  },
  {
    title: "Winsupply Corpus Christi 11",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-11.jpg",
  },
  {
    title: "Winsupply Corpus Christi 12",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-12.jpg",
  },
  {
    title: "Winsupply Corpus Christi 13",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-13.jpg",
  },
  {
    title: "Winsupply Corpus Christi 14",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-14.jpg",
  },
  {
    title: "Winsupply Corpus Christi 15",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-15.jpg",
  },
  {
    title: "Winsupply Corpus Christi 16",
    category: "Event coverage",
    metric: "Corporate event photography",
    imageSrc: "/assets/portfolio/event-coverage/winsupply-corpus-christi-16.jpg",
  },
];

const graphicsDesignLogoItems = [
  {
    title: "Baby Glimpse 1",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/baby-glimpse-01.jpg",
  },
  {
    title: "Baby Glimpse 2",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/baby-glimpse-02.jpg",
  },
  {
    title: "Baby Glimpse 3",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/baby-glimpse-03.jpg",
  },
  {
    title: "Baby Glimpse 4",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/baby-glimpse-04.jpg",
  },
  {
    title: "Baby Glimpse 5",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/baby-glimpse-05.jpg",
  },
  {
    title: "Baby Glimpse 6",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/baby-glimpse-06.jpg",
  },
  {
    title: "Baby Glimpse 7",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/baby-glimpse-07.jpg",
  },
  {
    title: "Baby Glimpse 8",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/baby-glimpse-08.jpg",
  },
  {
    title: "Essence Cater 1",
    category: "Brand application",
    metric: "Identity mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/essence-cater-01.jpg",
  },
  {
    title: "Essence Cater 2",
    category: "Brand application",
    metric: "Identity mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/essence-cater-02.jpg",
  },
  {
    title: "Essence Cater 3",
    category: "Brand application",
    metric: "Identity mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/essence-cater-03.jpg",
  },
  {
    title: "Essence Cater 4",
    category: "Brand application",
    metric: "Identity mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/essence-cater-04.jpg",
  },
  {
    title: "Essence Cater 5",
    category: "Brand application",
    metric: "Identity mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/essence-cater-05.jpg",
  },
  {
    title: "Essence Cater 6",
    category: "Brand application",
    metric: "Identity mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/essence-cater-06.jpg",
  },
  {
    title: "Essence Cater 7",
    category: "Brand application",
    metric: "Identity mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/essence-cater-07.jpg",
  },
  {
    title: "Essence Cater 8",
    category: "Brand application",
    metric: "Identity mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/essence-cater-08.jpg",
  },
  {
    title: "Essence Cater 9",
    category: "Brand application",
    metric: "Identity mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/essence-cater-09.jpg",
  },
  {
    title: "Essence Cater 10",
    category: "Brand application",
    metric: "Identity mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/essence-cater-10.jpg",
  },
  {
    title: "Essence Cater 11",
    category: "Brand application",
    metric: "Identity mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/essence-cater-11.jpg",
  },
  {
    title: "Essence Cater 12",
    category: "Brand application",
    metric: "Identity mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/essence-cater-12.jpg",
  },
  {
    title: "Next Level 1",
    category: "Brand guidelines",
    metric: "Visual identity system",
    imageSrc: "/assets/portfolio/graphics-design-logo/next-level-01.jpg",
  },
  {
    title: "Next Level 2",
    category: "Brand guidelines",
    metric: "Visual identity system",
    imageSrc: "/assets/portfolio/graphics-design-logo/next-level-02.jpg",
  },
  {
    title: "Next Level 3",
    category: "Brand guidelines",
    metric: "Visual identity system",
    imageSrc: "/assets/portfolio/graphics-design-logo/next-level-03.jpg",
  },
  {
    title: "Next Level 4",
    category: "Brand guidelines",
    metric: "Visual identity system",
    imageSrc: "/assets/portfolio/graphics-design-logo/next-level-04.jpg",
  },
  {
    title: "Next Level 5",
    category: "Brand guidelines",
    metric: "Visual identity system",
    imageSrc: "/assets/portfolio/graphics-design-logo/next-level-05.jpg",
  },
  {
    title: "Next Level 6",
    category: "Brand guidelines",
    metric: "Visual identity system",
    imageSrc: "/assets/portfolio/graphics-design-logo/next-level-06.jpg",
  },
  {
    title: "Next Level 7",
    category: "Brand guidelines",
    metric: "Visual identity system",
    imageSrc: "/assets/portfolio/graphics-design-logo/next-level-07.jpg",
  },
  {
    title: "Next Level 8",
    category: "Brand guidelines",
    metric: "Visual identity system",
    imageSrc: "/assets/portfolio/graphics-design-logo/next-level-08.jpg",
  },
  {
    title: "Next Level 9",
    category: "Brand guidelines",
    metric: "Visual identity system",
    imageSrc: "/assets/portfolio/graphics-design-logo/next-level-09.jpg",
  },
  {
    title: "Next Level 10",
    category: "Brand guidelines",
    metric: "Visual identity system",
    imageSrc: "/assets/portfolio/graphics-design-logo/next-level-10.jpg",
  },
  {
    title: "Next Level 11",
    category: "Brand guidelines",
    metric: "Visual identity system",
    imageSrc: "/assets/portfolio/graphics-design-logo/next-level-11.jpg",
  },
  {
    title: "Next Level 12",
    category: "Brand guidelines",
    metric: "Visual identity system",
    imageSrc: "/assets/portfolio/graphics-design-logo/next-level-12.jpg",
  },
  {
    title: "Next Level 13",
    category: "Brand guidelines",
    metric: "Visual identity system",
    imageSrc: "/assets/portfolio/graphics-design-logo/next-level-13.jpg",
  },
  {
    title: "Next Level 14",
    category: "Brand guidelines",
    metric: "Visual identity system",
    imageSrc: "/assets/portfolio/graphics-design-logo/next-level-14.jpg",
  },
  {
    title: "Elite Mindset 1",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/elite-mindset-01.jpg",
  },
  {
    title: "Elite Mindset 2",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/elite-mindset-02.jpg",
  },
  {
    title: "Elite Mindset 3",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/elite-mindset-03.jpg",
  },
  {
    title: "Elite Mindset 4",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/elite-mindset-04.jpg",
  },
  {
    title: "Elite Mindset 5",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/elite-mindset-05.jpg",
  },
  {
    title: "Elite Mindset 6",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/elite-mindset-06.jpg",
  },
  {
    title: "Elite Mindset 7",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/elite-mindset-07.jpg",
  },
  {
    title: "Elite Mindset 8",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/elite-mindset-08.jpg",
  },
  {
    title: "Holy Fish Logo 1",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-fish-logo-01.jpg",
  },
  {
    title: "Holy Fish Logo 2",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-fish-logo-02.jpg",
  },
  {
    title: "Holy Fish Logo 3",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-fish-logo-03.jpg",
  },
  {
    title: "Holy Fish Logo 4",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-fish-logo-04.jpg",
  },
  {
    title: "Holy Fish Logo 5",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-fish-logo-05.jpg",
  },
  {
    title: "Holy Fish Logo 6",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-fish-logo-06.jpg",
  },
  {
    title: "Holy Fish Logo 7",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-fish-logo-07.jpg",
  },
  {
    title: "Holy Fish Logo 8",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-fish-logo-08.jpg",
  },
  {
    title: "Quinpia Carwash 1",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/quinpia-carwash-01.jpg",
  },
  {
    title: "Quinpia Carwash 2",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/quinpia-carwash-02.jpg",
  },
  {
    title: "Quinpia Carwash 3",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/quinpia-carwash-03.jpg",
  },
  {
    title: "Quinpia Carwash 4",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/quinpia-carwash-04.jpg",
  },
  {
    title: "Quinpia Carwash 5",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/quinpia-carwash-05.jpg",
  },
  {
    title: "Quinpia Carwash 6",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/quinpia-carwash-06.jpg",
  },
  {
    title: "Quinpia Carwash 7",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/quinpia-carwash-07.jpg",
  },
  {
    title: "Twelves Burger 1",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/twelves-burger-01.jpg",
  },
  {
    title: "Twelves Burger 2",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/twelves-burger-02.jpg",
  },
  {
    title: "Twelves Burger 3",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/twelves-burger-03.jpg",
  },
  {
    title: "Twelves Burger 4",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/twelves-burger-04.jpg",
  },
  {
    title: "Twelves Burger 5",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/twelves-burger-05.jpg",
  },
  {
    title: "Twelves Burger 6",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/twelves-burger-06.jpg",
  },
  {
    title: "Twelves Burger 7",
    category: "Logo creation",
    metric: "Brand mockup",
    imageSrc: "/assets/portfolio/graphics-design-logo/twelves-burger-07.jpg",
  },
  {
    title: "Holy Nazarene 1",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-nazarene-01.jpg",
  },
  {
    title: "Holy Nazarene 2",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-nazarene-02.jpg",
  },
  {
    title: "Holy Nazarene 3",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-nazarene-03.jpg",
  },
  {
    title: "Holy Nazarene 4",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-nazarene-04.jpg",
  },
  {
    title: "Holy Nazarene 5",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-nazarene-05.jpg",
  },
  {
    title: "Holy Nazarene 6",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-nazarene-06.jpg",
  },
  {
    title: "Holy Nazarene 7",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-nazarene-07.jpg",
  },
  {
    title: "Holy Nazarene 8",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-nazarene-08.jpg",
  },
  {
    title: "Holy Nazarene 9",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-nazarene-09.jpg",
  },
  {
    title: "Holy Nazarene 10",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-nazarene-10.jpg",
  },
  {
    title: "Holy Nazarene 11",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-nazarene-11.jpg",
  },
  {
    title: "Holy Nazarene 12",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-nazarene-12.jpg",
  },
  {
    title: "Holy Nazarene 13",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/holy-nazarene-13.jpg",
  },
  {
    title: "Sageo 1",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/sageo-01.jpg",
  },
  {
    title: "Sageo 2",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/sageo-02.jpg",
  },
  {
    title: "Sageo 3",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/sageo-03.jpg",
  },
  {
    title: "Sageo 4",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/sageo-04.jpg",
  },
  {
    title: "Sageo 5",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/sageo-05.jpg",
  },
  {
    title: "Sageo 6",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/sageo-06.jpg",
  },
  {
    title: "Sageo 7",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/sageo-07.jpg",
  },
  {
    title: "Sageo 8",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/sageo-08.jpg",
  },
  {
    title: "Sageo 9",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/sageo-09.jpg",
  },
  {
    title: "Sageo 10",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/sageo-10.jpg",
  },
  {
    title: "Sageo 11",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/sageo-11.jpg",
  },
  {
    title: "Sageo 12",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/sageo-12.jpg",
  },
  {
    title: "Sageo 13",
    category: "Visual identity",
    metric: "Identity presentation",
    imageSrc: "/assets/portfolio/graphics-design-logo/sageo-13.jpg",
  },
  {
    title: "Beacon 57 1",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/beacon-57-01.jpg",
  },
  {
    title: "Beacon 57 2",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/beacon-57-02.jpg",
  },
  {
    title: "Beacon 57 3",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/beacon-57-03.jpg",
  },
  {
    title: "Beacon 57 4",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/beacon-57-04.jpg",
  },
  {
    title: "Beacon 57 5",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/beacon-57-05.jpg",
  },
  {
    title: "Beacon 57 6",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/beacon-57-06.jpg",
  },
  {
    title: "Crawfish for a Cause 1",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/crawfish-for-a-cause-01.jpg",
  },
  {
    title: "Crawfish for a Cause 2",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/crawfish-for-a-cause-02.jpg",
  },
  {
    title: "Crawfish for a Cause 3",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/crawfish-for-a-cause-03.jpg",
  },
  {
    title: "Crawfish for a Cause 4",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/crawfish-for-a-cause-04.jpg",
  },
  {
    title: "Crawfish for a Cause 5",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/crawfish-for-a-cause-05.jpg",
  },
  {
    title: "Crawfish for a Cause 6",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/crawfish-for-a-cause-06.jpg",
  },
  {
    title: "Harbor Half Marathon 1",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/harbor-half-marathon-01.jpg",
  },
  {
    title: "Harbor Half Marathon 2",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/harbor-half-marathon-02.jpg",
  },
  {
    title: "Harbor Half Marathon 3",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/harbor-half-marathon-03.jpg",
  },
  {
    title: "Hotel Lydia Events 1",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/hotel-lydia-events-01.jpg",
  },
  {
    title: "Hotel Lydia Events 2",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/hotel-lydia-events-02.jpg",
  },
  {
    title: "Hotel Lydia Events 3",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/hotel-lydia-events-03.jpg",
  },
  {
    title: "Hotel Lydia Rooms 1",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/hotel-lydia-rooms-01.jpg",
  },
  {
    title: "Hotel Lydia Rooms 2",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/hotel-lydia-rooms-02.jpg",
  },
  {
    title: "Hotel Lydia Rooms 3",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/hotel-lydia-rooms-03.jpg",
  },
  {
    title: "Hotel Lydia Rooms 4",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/hotel-lydia-rooms-04.jpg",
  },
  {
    title: "Memory Machine 1",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/memory-machine-01.jpg",
  },
  {
    title: "Memory Machine 2",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/memory-machine-02.jpg",
  },
  {
    title: "Memory Machine 3",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/memory-machine-03.jpg",
  },
  {
    title: "Memory Machine 4",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/memory-machine-04.jpg",
  },
  {
    title: "Memory Machine 5",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/memory-machine-05.jpg",
  },
  {
    title: "The Bar & Grill 1",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/the-bar-and-grill-01.jpg",
  },
  {
    title: "The Bar & Grill 2",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/the-bar-and-grill-02.jpg",
  },
  {
    title: "The Bar & Grill 3",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/the-bar-and-grill-03.jpg",
  },
  {
    title: "The Bar & Grill 4",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/the-bar-and-grill-04.jpg",
  },
  {
    title: "The Bar & Grill 5",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/the-bar-and-grill-05.jpg",
  },
  {
    title: "The Bar & Grill 6",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/the-bar-and-grill-06.jpg",
  },
  {
    title: "The Bar & Grill 7",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/the-bar-and-grill-07.jpg",
  },
  {
    title: "The Bar & Grill 8",
    category: "Social media artcard",
    metric: "Campaign graphic",
    imageSrc: "/assets/portfolio/graphics-design-logo/the-bar-and-grill-08.jpg",
  },
];

const photographyItems = [
  {
    title: "Hotel Lydia 1",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-01.jpg",
  },
  {
    title: "Hotel Lydia 2",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-02.jpg",
  },
  {
    title: "Hotel Lydia 3",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-03.jpg",
  },
  {
    title: "Hotel Lydia 4",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-04.jpg",
  },
  {
    title: "Hotel Lydia 5",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-05.jpg",
  },
  {
    title: "Hotel Lydia 6",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-06.jpg",
  },
  {
    title: "Hotel Lydia 7",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-07.jpg",
  },
  {
    title: "Hotel Lydia 8",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-08.jpg",
  },
  {
    title: "Hotel Lydia 9",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-09.jpg",
  },
  {
    title: "Hotel Lydia 10",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-10.jpg",
  },
  {
    title: "Hotel Lydia 11",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-11.jpg",
  },
  {
    title: "Hotel Lydia 12",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-12.jpg",
  },
  {
    title: "Hotel Lydia 13",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-13.jpg",
  },
  {
    title: "Hotel Lydia 14",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-14.jpg",
  },
  {
    title: "Hotel Lydia 15",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-15.jpg",
  },
  {
    title: "Hotel Lydia 16",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-16.jpg",
  },
  {
    title: "Hotel Lydia 17",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-17.jpg",
  },
  {
    title: "Hotel Lydia 18",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-18.jpg",
  },
  {
    title: "Hotel Lydia 19",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-19.jpg",
  },
  {
    title: "Hotel Lydia 20",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-20.jpg",
  },
  {
    title: "Hotel Lydia 21",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-21.jpg",
  },
  {
    title: "Hotel Lydia 22",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-22.jpg",
  },
  {
    title: "Hotel Lydia 23",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-23.jpg",
  },
  {
    title: "Hotel Lydia 24",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-24.jpg",
  },
  {
    title: "Hotel Lydia 25",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-25.jpg",
  },
  {
    title: "Hotel Lydia 26",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-26.jpg",
  },
  {
    title: "Hotel Lydia 27",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-27.jpg",
  },
  {
    title: "Hotel Lydia 28",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-28.jpg",
  },
  {
    title: "Hotel Lydia 29",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-29.jpg",
  },
  {
    title: "Hotel Lydia 30",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-30.jpg",
  },
  {
    title: "Hotel Lydia 31",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-31.jpg",
  },
  {
    title: "Hotel Lydia 32",
    category: "Commercial photography",
    metric: "Hospitality photography",
    imageSrc: "/assets/portfolio/photography/hotel-lydia-32.jpg",
  },
  {
    title: "Headshots & Portraits 1",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-01.jpg",
  },
  {
    title: "Headshots & Portraits 2",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-02.jpg",
  },
  {
    title: "Headshots & Portraits 3",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-03.jpg",
  },
  {
    title: "Headshots & Portraits 4",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-04.jpg",
  },
  {
    title: "Headshots & Portraits 5",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-05.jpg",
  },
  {
    title: "Headshots & Portraits 6",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-06.jpg",
  },
  {
    title: "Headshots & Portraits 7",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-07.jpg",
  },
  {
    title: "Headshots & Portraits 8",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-08.jpg",
  },
  {
    title: "Headshots & Portraits 9",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-09.jpg",
  },
  {
    title: "Headshots & Portraits 10",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-10.jpg",
  },
  {
    title: "Headshots & Portraits 11",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-11.jpg",
  },
  {
    title: "Headshots & Portraits 12",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-12.jpg",
  },
  {
    title: "Headshots & Portraits 13",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-13.jpg",
  },
  {
    title: "Headshots & Portraits 14",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-14.jpg",
  },
  {
    title: "Headshots & Portraits 15",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-15.jpg",
  },
  {
    title: "Headshots & Portraits 16",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-16.jpg",
  },
  {
    title: "Headshots & Portraits 17",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-17.jpg",
  },
  {
    title: "Headshots & Portraits 18",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-18.jpg",
  },
  {
    title: "Headshots & Portraits 19",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-19.jpg",
  },
  {
    title: "Headshots & Portraits 20",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-20.jpg",
  },
  {
    title: "Headshots & Portraits 21",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-21.jpg",
  },
  {
    title: "Headshots & Portraits 22",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-22.jpg",
  },
  {
    title: "Headshots & Portraits 23",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-23.jpg",
  },
  {
    title: "Headshots & Portraits 24",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-24.jpg",
  },
  {
    title: "Headshots & Portraits 25",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-25.jpg",
  },
  {
    title: "Headshots & Portraits 26",
    category: "Headshot photography",
    metric: "Portrait session",
    imageSrc: "/assets/portfolio/photography/headshots-and-portraits-26.jpg",
  },
  {
    title: "Product Shoots 1",
    category: "Product photography",
    metric: "Commercial product detail",
    imageSrc: "/assets/portfolio/photography/product-shoots-01.jpg",
  },
  {
    title: "Product Shoots 2",
    category: "Product photography",
    metric: "Commercial product detail",
    imageSrc: "/assets/portfolio/photography/product-shoots-02.jpg",
  },
  {
    title: "Product Shoots 3",
    category: "Product photography",
    metric: "Commercial product detail",
    imageSrc: "/assets/portfolio/photography/product-shoots-03.jpg",
  },
  {
    title: "Product Shoots 4",
    category: "Product photography",
    metric: "Commercial product detail",
    imageSrc: "/assets/portfolio/photography/product-shoots-04.jpg",
  },
  {
    title: "Product Shoots 5",
    category: "Product photography",
    metric: "Commercial product detail",
    imageSrc: "/assets/portfolio/photography/product-shoots-05.jpg",
  },
  {
    title: "Product Shoots 6",
    category: "Product photography",
    metric: "Commercial product detail",
    imageSrc: "/assets/portfolio/photography/product-shoots-06.jpg",
  },
  {
    title: "Product Shoots 7",
    category: "Product photography",
    metric: "Commercial product detail",
    imageSrc: "/assets/portfolio/photography/product-shoots-07.jpg",
  },
  {
    title: "Product Shoots 8",
    category: "Product photography",
    metric: "Commercial product detail",
    imageSrc: "/assets/portfolio/photography/product-shoots-08.jpg",
  },
  {
    title: "Product Shoots 9",
    category: "Product photography",
    metric: "Commercial product detail",
    imageSrc: "/assets/portfolio/photography/product-shoots-09.jpg",
  },
  {
    title: "Product Shoots 10",
    category: "Product photography",
    metric: "Commercial product detail",
    imageSrc: "/assets/portfolio/photography/product-shoots-10.jpg",
  },
  {
    title: "Product Shoots 11",
    category: "Product photography",
    metric: "Commercial product detail",
    imageSrc: "/assets/portfolio/photography/product-shoots-11.jpg",
  },
  {
    title: "Product Shoots 12",
    category: "Product photography",
    metric: "Commercial product detail",
    imageSrc: "/assets/portfolio/photography/product-shoots-12.jpg",
  },
];

const videoProductionItems = [
  {
    title: "Bradley's Motors 1",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/bradley-s-motors/bradley-s-motors-01.jpg",
    videoSrc: "/assets/portfolio/video-production/bradley-s-motors/bradley-s-motors-01.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Bradley's Motors 2",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/bradley-s-motors/bradley-s-motors-02.jpg",
    videoSrc: "/assets/portfolio/video-production/bradley-s-motors/bradley-s-motors-02.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Video Production 1",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/general-video-production/general-video-production-01.jpg",
    videoSrc: "/assets/portfolio/video-production/general-video-production/general-video-production-01.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Video Production 2",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/general-video-production/general-video-production-02.jpg",
    videoSrc: "/assets/portfolio/video-production/general-video-production/general-video-production-02.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Video Production 3",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/general-video-production/general-video-production-03.jpg",
    videoSrc: "/assets/portfolio/video-production/general-video-production/general-video-production-03.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Video Production 4",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/general-video-production/general-video-production-04.jpg",
    videoSrc: "/assets/portfolio/video-production/general-video-production/general-video-production-04.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Video Production 5",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/general-video-production/general-video-production-05.jpg",
    videoSrc: "/assets/portfolio/video-production/general-video-production/general-video-production-05.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Habitat for Humanity 1",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/habitat-for-humanity/habitat-for-humanity-01.jpg",
    videoSrc: "/assets/portfolio/video-production/habitat-for-humanity/habitat-for-humanity-01.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Habitat for Humanity 2",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/habitat-for-humanity/habitat-for-humanity-02.jpg",
    videoSrc: "/assets/portfolio/video-production/habitat-for-humanity/habitat-for-humanity-02.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Habitat for Humanity 3",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/habitat-for-humanity/habitat-for-humanity-03.jpg",
    videoSrc: "/assets/portfolio/video-production/habitat-for-humanity/habitat-for-humanity-03.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Habitat for Humanity 4",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/habitat-for-humanity/habitat-for-humanity-04.jpg",
    videoSrc: "/assets/portfolio/video-production/habitat-for-humanity/habitat-for-humanity-04.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Habitat for Humanity 5",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/habitat-for-humanity/habitat-for-humanity-05.jpg",
    videoSrc: "/assets/portfolio/video-production/habitat-for-humanity/habitat-for-humanity-05.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Lost Travel 1",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/lost-travel/lost-travel-01.jpg",
    videoSrc: "/assets/portfolio/video-production/lost-travel/lost-travel-01.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Lost Travel 2",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/lost-travel/lost-travel-02.jpg",
    videoSrc: "/assets/portfolio/video-production/lost-travel/lost-travel-02.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Lost Travel 3",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/lost-travel/lost-travel-03.jpg",
    videoSrc: "/assets/portfolio/video-production/lost-travel/lost-travel-03.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Lost Travel 4",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/lost-travel/lost-travel-04.jpg",
    videoSrc: "/assets/portfolio/video-production/lost-travel/lost-travel-04.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Lost Travel 5",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/lost-travel/lost-travel-05.jpg",
    videoSrc: "/assets/portfolio/video-production/lost-travel/lost-travel-05.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
  {
    title: "Lost Travel 6",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/lost-travel/lost-travel-06.jpg",
    videoSrc: "/assets/portfolio/video-production/lost-travel/lost-travel-06.mp4",
    mediaType: "video",
    orientation: "portrait",
  },
  {
    title: "Lost Travel 7",
    category: "Video production",
    metric: "Campaign video",
    imageSrc: "/assets/portfolio/video-production/lost-travel/lost-travel-07.jpg",
    videoSrc: "/assets/portfolio/video-production/lost-travel/lost-travel-07.mp4",
    mediaType: "video",
    orientation: "landscape",
  },
];

export const portfolioCategories = [
  {
    title: "Content Creation",
    slug: "content-creation",
    items: contentCreationItems,
  },
  {
    title: "Event Coverage",
    slug: "event-coverage",
    items: eventCoverageItems,
  },
  {
    title: "Video Production",
    slug: "video-production",
    items: videoProductionItems,
  },
  {
    title: "Graphics Design\n& Logo Creation",
    slug: "graphics-design-logo-creation",
    items: graphicsDesignLogoItems,
  },
  {
    title: "Photography",
    slug: "photography-commercial-product-headshots",
    items: photographyItems,
  },
  {
    title: "Brand Strategy, Kit,\n& Guidelines",
    slug: "brand-strategy-kit-guidelines",
    note: "Samples Available Upon Request",
    items: [],
  },
  {
    title: "Social Media\nManagement",
    slug: "social-media-management",
    note: "Samples Available Upon Request",
    items: [],
  },
];

export const partnerLogos = [
  {
    name: "Habitat for Humanity Corpus Christi",
    src: "/assets/clients/client-habitat-for-humanity-corpus-christi.png",
  },
  {
    name: "Harbor Half Marathon",
    src: "/assets/clients/client-harbor-half-marathon.png",
  },
  {
    name: "Crawfish for a Cause Corpus Christi",
    src: "/assets/clients/client-crawfish-for-a-cause-corpus-christi.png",
  },
  {
    name: "Discover Aransas County",
    src: "/assets/clients/client-discover-aransas-county.png",
  },
  {
    name: "Coastal Bend Filipino-American Association",
    src: "/assets/clients/client-coastal-bend-filam-association.png",
  },
  {
    name: "Hotel Lydia",
    src: "/assets/clients/client-hotel-lydia.png",
  },
  {
    name: "Beacon at Hotel Lydia",
    src: "/assets/clients/client-beacon-at-hotel-lydia.png",
  },
  {
    name: "The Bar & Grill Corpus Christi",
    src: "/assets/clients/client-the-bar-and-grill-corpus-christi.png",
  },
  {
    name: "Winsupply of Corpus Christi Plumbing",
    src: "/assets/clients/client-winsupply-corpus-christi.png",
  },
  {
    name: "Burapha University Graduate School",
    src: "/assets/clients/client-burapha-university-graduate-school.png",
  },
  {
    name: "Joe A. Gonzalez Education is Freedom Scholarship Program",
    src: "/assets/clients/client-education-is-freedom-scholarship-program.png",
  },
  {
    name: "Lost Travel",
    src: "/assets/clients/client-lost-travel.png",
    scale: 0.64,
  },
];

export const phoneShowcaseScreens = [
  {
    title: "Hotel Lydia analytics",
    label: "Performance",
    src: "/assets/phone-showcase/screen-hotel-lydia-analytics.png",
    width: 1080,
    height: 1920,
  },
  {
    title: "Hotel Lydia profile",
    label: "Profile system",
    src: "/assets/phone-showcase/screen-hotel-lydia-social-profile.png",
    width: 1080,
    height: 2570,
    scrollable: true,
  },
  {
    title: "Harbor Half content",
    label: "Event coverage",
    src: "/assets/phone-showcase/screen-harbor-half-social-content.png",
    width: 1080,
    height: 1920,
  },
];

export const testimonials = [
  {
    quote:
      "Scattered ideas become a clear campaign system.",
    name: "Founder track",
    role: "Brand launch",
  },
  {
    quote:
      "Creative arrives polished, organized, and ready for channels.",
    name: "Marketing track",
    role: "Content cycle",
  },
  {
    quote:
      "Direction, production, and review stay aligned.",
    name: "Production track",
    role: "Asset buildout",
  },
];

export const processSteps = [
  {
    number: "01",
    title: "Clarify the gap.",
    headingLines: ["Clarify", "the gap."],
    body: "We review your brand, audience, channels, and current content to identify what needs to become clearer before production begins.",
    imageSrc: "/assets/process/process-clarify-gap.png",
    imageAlt: "Creative notes and brand audit materials for the clarify stage",
    focus: "Brand audit",
    outputs: ["Audience lens", "Channel review", "Content gaps"],
  },
  {
    number: "02",
    title: "Shape the direction.",
    headingLines: ["Shape the", "direction."],
    body: "Research becomes a focused creative direction: what to make, where it belongs, and how each piece should support the brand.",
    imageSrc: "/assets/process/process-shape-direction.png",
    imageAlt: "Visual direction board for campaign planning",
    focus: "Creative route",
    outputs: ["Mood system", "Shot plan", "Campaign map"],
  },
  {
    number: "03",
    title: "Build the assets.",
    headingLines: ["Build the", "assets."],
    body: "Photography, video, graphics, and social assets are produced with enough range to launch across your digital footprint.",
    imageSrc: "/assets/process/process-build-assets.png",
    imageAlt: "Produced social and digital content assets",
    focus: "Production",
    outputs: ["Video cuts", "Photo selects", "Design files"],
  },
  {
    number: "04",
    title: "Refine the next round.",
    headingLines: ["Refine the", "next round."],
    body: "Performance, feedback, and team notes shape the next round so your content system becomes sharper over time.",
    imageSrc: "/assets/process/process-refine-round.png",
    imageAlt: "Review notes and refinements for the next content round",
    focus: "Iteration",
    outputs: ["Results read", "Feedback pass", "Next brief"],
  },
];

export const stats = [
  { value: "6", label: "Creative services" },
  { value: "1", label: "Content workflow" },
  { value: "Web", label: "Social + launch assets" },
];
